<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="UTF-8">
	  <title> first page </title>
	  
  <style>
  *{
    box-sizing: border-box;
	margin: 0px;
	padding 0px;
   }
<h1>
  {
     margin: 50px;
   }	
   </h1>
     .container{
         width: 95%;
         overflow: hidden;
         margin: 20px auto;
         padding: 20px 0px;	
     
	 }
	 .container ul{
	          margin: 0px;
	          padding 0px;
	 }
	 .container ul li{
	 
	 list-style: none;
	 float: left;
	 width: 25%;
	 height: 500px;
	 background-color: gray;
	 margin: 30px 20px 0px 30px;
	 box-sizing: border-box;
	 border: 2px solid black;
	 }   
     .container ul li:hover{
	     opacity:0.9;
		 }
		  .container ul li .title:hover{
		  background: white;
		  color: red;
		  
		  
		  }
    .container ul li .title{
	 width: 100%;
	 height: 50px;
	 line-height: 50px;
	 background: red;
	 text-align: center;
     }  	 
	  @media screen and (max-width:1250px){
	  .container ul li{
	  width: 40%;
	  margin-left: 40px;
	  }
	  }
	  
	</style>
    </head>
 <body>
    <h1 style = "text-align: center";> OUR MENU </h1>
	<div class ="container">
	<ul>
	  <li> <div class="title">PANI PURI <p id="p1">Pani Literally translates to water and here the Puris are fried puffed crisp dough balls which are hollow. Generally, the water or pani is sour, tangy as well as spicy. This spicy pani is balanced with the addition of sweet tamarind chutney.This sweet chutney is called as Meetha (which means sweet) Pani. The spicy water is called as Teekha (which means spicy) Pani. both are added in the puri along with the main filling which consists of boiled potatoes.</p1></li>
	  
	  <li> <div class="title">PAV BHAJI <p id="p2">The boiled veggies are cooked with a special blend of spices known as pav bhaji masala. You can get this masala easily at any Indian store. It's a blend of spices like coriander, cumin seeds, fennel, cinnamon, amchur (dried mango powder) and more.</p1></li>
	  <li> <div class="title">SOUTH INDIAN DOSA <p id="p3">Dosa can be stuffed with fillings of vegetables and sauces to make a quick meal. They are typically served with a vegetarian side dish which varies according to regional and personal preferences.Variations:Masala dosa, rava dosa, ghee roast dosa, neer dosa and many mor</p1>

</li>
 	  
	
 </ul>
	</div>
 </body>

</html>
